### ISSUE TITLE
UserController endpoint: "/user/sigin" throwing "500" Internal Server Error

### ISSUE THREAD

**Issue by Tejas-Teju** [exynerve/quora-project#6]
Response Body: 
{
  "timestamp": "2021-01-25T16:08:31.408+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "No message available",
  "path": "/api/user/signin"
}

**Comment by exynerve** [comment]
Resolved with fresh commits

**Comment by Tejas-Teju** [comment]
Commit "584421aea28b5a9ff98508355c6303c0c9ad846b" resolved the issue. 

Thanks Prajwal for fixing it.
